micronaut:
  application:
    name: demo

############################# DB ################################

dataSource:
  #  dbCreate: none, update, or create-drop
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  dbCreate: update
  url: ${MYSQL_URL:`jdbc:mysql://localhost:6603/demo?useSSL=false`}
  username: ${MYSQL_USER:demouser}
  password: ${MYSQL_PASSWORD:demopasswd}
  driverClassName: com.mysql.cj.jdbc.Driver
  pooled: true
  #  jmxExport: true
  maximumPoolSize: ${DB_MAX_POOL_SIZE:10}
  minimumIdle: 5

hibernate:
  show_sql: false
#  hbm2ddl:
#    auto: create-drop
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
